capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("user.urls")),
    path('',include("polls.urls")),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.index, name="index"),
    # Index of user polls, add new poll
    path('myIndex/',views.my_polls,name='my_index'),
    # Voting Page
    path('polls/votingPage/<str:poll_name>/',views.votingPage,name='voting_page'),
    path('polls/votingPage/<str:poll_name>/<str:preview>/',views.votingPage,name='voting_pagePreview'),

    # Get poll groups - javascript fetch api
    path('polls/getGroups/<str:poll_name>/',views.get_groups,name='getGroups'),
    # Get group categories - javascript fetch api
    path('polls/getCategories/<str:poll_name>/<str:group_name>/',views.get_categories,name='getCategories'),
    # Get category candidates - javascript fetch api
    path('polls/getCandidates/<str:poll_name>/<str:category_name>/',views.get_candidates,name='getCandidates'),
    # Vote - javascript fetch api
    path('polls/vote/<str:poll_name>/',views.vote,name='vote'),
    # Results
    path('polls/resultsIndex/',views.results_index,name='results_index'),
    path('polls/results/<str:poll_name>/',views.resultsPage,name='resultsPage'),
    path('polls/get_results/<str:poll_name>/<str:category_name>/<str:sort>/',views.results,name='results'),
    
    ## MANAGEING POLL(ADMIN/CREATOR)
    # Manage poll, add category, add candidate
    path('polls/manage/<str:poll_name>/<str:view>/',views.poll_management,name='poll_management'),

    # Get all categories
    path('polls/<str:poll_name>/management/categories/', views.manage_categories, name ="categories_management"),

    # Get all candidates
    path('polls/<str:poll_name>/management/candidates/', views.manage_candidates, name ="candidates_management"),

    # Manage settings
    path('polls/<str:poll_name>/management/settings/', views.manage_settings, name ="settings_management"),

    # Manage keys
    path('polls/<str:poll_name>/management/keys/', views.poll_keys, name ="keys_management"),

    # Keys Upload and Print(Excel)
    path('polls/<str:poll_name>/Excelkeys/', views.excel_keys, name ="keys_excel"),

     # Input Key
    path('polls/<str:poll_name>/inputKey/', views.input_key, name ="input_key")

]

user/urls.py
from django.urls import path
from . import views


app_name = "user"

urlpatterns = [
    # SignIn and Registration
    path('register/',views.register_view,name='register'),
    path('login/',views.login_view,name="login" ),
    path('logout/',views.logout_view,name="logout" ),
    path('activate/<str:username>/', views.activate_user, name="activate_user"),
    
    # Profile page
    path('user/profile/', views.user_profile, name="user_profile"),

    # Edits
    path('user/edit/', views.edit_profile, name="edit_profile"),
    path('reset_password/<int:user_id>/' ,views.reset_password_page, name = "reset_password_page"),
    path('send_reset_email/' ,views.reset_password_email, name = "reset_password_email"),
    path('user/change_password/', views.change_password, name = "change_password"),
]

polls/forms.py
from django import forms
from .models import Poll, Candidate

class PollForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control-file'}))
    closing_date = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control','type':'date'}))

    class Meta:
        model = Poll
        fields = ('name','image','closing_date','restrictionType','live_results')

    def __init__(self, *args, **kwargs):
        super(PollForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Title"

class CandidateForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    party = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=False)
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control-file'}),required=False)

    class Meta:
        model = Candidate
        fields= "__all__"
        exclude=['poll','categories_contesting']

class EditPollForm(forms.Form):
    name = forms.CharField()
    image = forms.ImageField(required=False)
    restrictionType = forms.CharField()
    closing_date = forms.DateField()
    live_results = forms.BooleanField(required=False)

class KeyForm(forms.Form):
    key = forms.CharField()

polls/views.py
from django.http.response import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
import json
import pandas
from io import BytesIO


from .models import Poll, PollCategory, Candidate, PollCategoryGroup, RestrictionKey, Vote
from .forms import PollForm, CandidateForm, EditPollForm, KeyForm

# Page of active and unhidden polls
def index(request):
    polls = Poll.objects.filter(active=True, hidden=False)
    paginator = Paginator(polls, 10) # Show 10 items per page.
    page_number = request.GET.get('page')
    polls = paginator.get_page(page_number)
    context ={
        "polls":polls,
        "page":"home"
    }
    return render(request, "polls/index.html",context)

# Index of all created polls and add new poll form
@login_required(login_url = 'user:login')
def my_polls(request):
    form = PollForm()
    error_messages = []
    
    # Create a new poll
    if request.method == "POST":
        # # Limit number of user polls to 3
        # if Poll.objects.filter(creator = request.user).count() > 2:
        #     error_messages.append("User can only create a maximum of 3 polls")

        form = PollForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                Poll.objects.create(
                    creator = request.user,
                    name = form.cleaned_data['name'],
                    image = form.cleaned_data['image'] ,
                    closing_date = form.cleaned_data['closing_date'],
                    restrictionType = form.cleaned_data['restrictionType'],
                    live_results = form.cleaned_data['live_results'] 
                )
                return HttpResponseRedirect(reverse('polls:my_index'))
            except Exception as e:
                error_messages.append(e)
                print(e)
        else:
            for field in form:   
                for error in field.errors:   
                    error_messages.append(error.capitalize())

    polls = Poll.objects.filter(creator = request.user)
    paginator = Paginator(polls, 10) # Show 10 items per page.
    page_number = request.GET.get('page')
    polls = paginator.get_page(page_number)

    context ={
        "form":form,
        "polls":polls,
        "error_messages":error_messages,
        "page":"myPolls"
    }
    return render(request, "polls/my_index.html",context)

# Get available groups for the poll, returned as json
@login_required(login_url = 'user:login')
def get_groups(request,poll_name):
    poll_name = poll_name.lower()
    poll = Poll.objects.get(name = poll_name)
    groups = poll.groups.all()
    return JsonResponse([group.serialize() for group in groups],safe=False)

# Get available candidates for the selected category, returned as json
@login_required(login_url = 'user:login')
def get_candidates(request,poll_name,category_name):
    poll_name = poll_name.lower()
    category_name = category_name.lower()
    category = PollCategory.objects.get(poll__name = poll_name, name = category_name)
    candidates = category.candidates.all()
    return JsonResponse([candidate.serialize() for candidate in candidates],safe=False)

# Get available categories for the poll either all or by the group selected, returned as json
@login_required(login_url = 'user:login')
def get_categories(request,poll_name,group_name):
    poll_name = poll_name.lower()
    group_name = group_name.lower()
    poll = Poll.objects.get(name = poll_name)
    if group_name == "none":
        categories = poll.categories.all()
    else:   
        group= poll.groups.all().get(name = group_name)
        categories = group.categories.all()
    return JsonResponse([category.serialize() for category in categories],safe=False)

# Manage poll settings, groups, categories and candidates
@login_required(login_url = 'user:login')
def poll_management(request,poll_name,view):
    poll_name = poll_name.lower()
    view = view.lower()
    poll = Poll.objects.get(name = poll_name)
    poll.deadline() # check and update poll status considering the poll deadline
    # Check for creator and give access or deny
    if poll.creator != request.user:
        raise Http404
    # Default view is categories if none of the accepted views is provided
    if view != "categories" and view !="candidates" and view != "settings":
        view = "categories"
    context ={
        "view":view,
        "poll":poll,
    }
    return render(request, "polls/management.html",context)

# Handle api requests to poll categories for creation, editing, deleting of poll category
@login_required(login_url = 'user:login')
def manage_categories(request,poll_name):
    poll_name = poll_name.lower()
    poll = Poll.objects.get(name = poll_name)

    # Check for creator and give access
    if poll.creator != request.user:
        raise Http404
    # Return poll categories in json
    if request.method == "GET":
        categories = poll.categories.all()
        return JsonResponse([category.serialize() for category in categories],safe=False)

    # Can only edit, create and delete only inactive polls
    if poll.active:
        return HttpResponse(status = 403)
    elif request.method == "POST":
        data = json.loads(request.body)
        # Get new polls name from json data
        name = data['name']
        # Default group selected to none
        group = None
        # Get the group object if a group was provided
        if data['group']:
            try:
                group = poll.groups.all.get(name = data["group"])
            except Exception as e:
                print(e)
        # Check against empty name and then save new poll
        if name.split():
            try:
                PollCategory.objects.create(
                    poll = poll,
                    name = name,
                    group = group
                )
                return HttpResponse(status = 201)
            except Exception as e:
                print(e)
                return HttpResponse(status = 400)

    # Editing an already existing category
    elif request.method == "PUT":
        data = json.loads(request.body)
        # Select category by id provided
        category_id = data['id']
        category = poll.categories.all().get(id = category_id)
        
        # Request to remove link of all candidates to this category
        if data['action'] == "clear_candidates":
            candidates = category.candidates.all()
            for candidate in candidates:
                candidate.categories_contesting.remove(category)
            return HttpResponse(status = 201)
        
        # Handle replacing category name and also changing the group it is under
        new_name = data['name']
        new_group_name = data['group_name']

        if new_name.split():
            category.name = new_name
        if new_group_name:
            new_group = poll.groups.all().get(name = new_group_name)
            category.group = new_group
        try:
            category.save()
            return HttpResponse(status = 201)
        except Exception as e:
            print(e)
            return HttpResponse(status=400)

    # Delete category from the poll
    elif request.method == "DELETE":
        data = json.loads(request.body)
        category_id = data['id']
        category = poll.categories.all().get(id = category_id)
        category.delete()
        return HttpResponse(status = 201)

# Handle access, creation and deletion of candidates to poll
@login_required(login_url = 'user:login')
def manage_candidates(request,poll_name):
    poll_name = poll_name.lower()
    poll = Poll.objects.get(name = poll_name)

    # Check for creator and give access or deny
    if poll.creator != request.user:
        raise Http404
    
    # Return all candidates data in json 
    if request.method == "GET":
        candidates = poll.candidates.all()
        return JsonResponse([candidate.serialize() for candidate in candidates],safe=False)
    
    # Cannot edit or save candidate in an active poll
    if poll.active:
        return HttpResponse(status = 403)
        
    elif request.method == "POST":
        candidate_form = CandidateForm(request.POST , request.FILES)
        categories = request.POST["categories"].split(',')   
        print(request.POST['party'])
        if candidate_form.is_valid():
            print(candidate_form.cleaned_data["party"])
            # Create a new candidate
            if request.POST['form_type'] == "new_candidate":
                try:
                    candidate = Candidate.objects.create(
                        poll = poll,
                        name = candidate_form.cleaned_data["name"],
                        party = candidate_form.cleaned_data["party"],
                        image = candidate_form.cleaned_data["image"]
                    )
                    for category in categories:
                        try:
                            category = poll.categories.all().get(name = category)
                            candidate.categories_contesting.add(category)
                        except Exception as e:
                            print(e)
                    candidate.save()
                    return HttpResponse(status=201)
                except Exception as e:
                    print("error: ",e)

            # Edit an already existing candidate's data
            elif request.POST['form_type'] == "edit_candidate":
                candidate = poll.candidates.all().get(id = request.POST['candidate_id'])
                candidate.name = candidate_form.cleaned_data["name"]
                candidate.party = candidate_form.cleaned_data["party"] 
                new_image = candidate_form.cleaned_data["image"]
                candidate.categories_contesting.clear()
                if new_image:

polls/templates/polls/index.html
{% extends 'theSP/layout.html' %}
{% load static %}

{% block title %} Home {% endblock title%}

{% block body %}
    <div class="header">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="height: 100%;">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" style="height: 100%;">
              <div class="carousel-item active">
                <img src="{% static 'images/header.jpg' %}" style="object-fit: fill;" class="d-block w-100" alt="carasol1">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/header2.jpg' %}" style="object-fit:fill;" class="d-block w-100" alt="carasol2">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/header4.jpg' %}" style="object-fit:fill;" class="d-block w-100" alt="carasol3">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="container" style="margin-top: 10em;">
        <div class="index row">
            {% for poll in polls %}
                <div class="index-card col-md-12 index-card-small">
                    <div class="card">
                        <div class="image">
                            <img src={{poll.image.url}} alt="image-{{poll.name}}">
                        </div>
                        <div class="details">
                            <div class="description"">
                                <h2 class="name">
                                    {{poll.name}} 
                                </h2>
                            </div>
                            <div class="links">
                                <a class="btn btn-outline-primary" href = "{{poll.get_absolute_url}}">
                                    GO VOTE
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-index-thumb" viewBox="0 0 16 16">
                                        <path d="M6.75 1a.75.75 0 0 1 .75.75V8a.5.5 0 0 0 1 0V5.467l.086-.004c.317-.012.637-.008.816.027.134.027.294.096.448.182.077.042.15.147.15.314V8a.5.5 0 0 0 1 0V6.435l.106-.01c.316-.024.584-.01.708.04.118.046.3.207.486.43.081.096.15.19.2.259V8.5a.5.5 0 1 0 1 0v-1h.342a1 1 0 0 1 .995 1.1l-.271 2.715a2.5 2.5 0 0 1-.317.991l-1.395 2.442a.5.5 0 0 1-.434.252H6.118a.5.5 0 0 1-.447-.276l-1.232-2.465-2.512-4.185a.517.517 0 0 1 .809-.631l2.41 2.41A.5.5 0 0 0 6 9.5V1.75A.75.75 0 0 1 6.75 1zM8.5 4.466V1.75a1.75 1.75 0 1 0-3.5 0v6.543L3.443 6.736A1.517 1.517 0 0 0 1.07 8.588l2.491 4.153 1.215 2.43A1.5 1.5 0 0 0 6.118 16h6.302a1.5 1.5 0 0 0 1.302-.756l1.395-2.441a3.5 3.5 0 0 0 .444-1.389l.271-2.715a2 2 0 0 0-1.99-2.199h-.581a5.114 5.114 0 0 0-.195-.248c-.191-.229-.51-.568-.88-.716-.364-.146-.846-.132-1.158-.108l-.132.012a1.26 1.26 0 0 0-.56-.642 2.632 2.632 0 0 0-.738-.288c-.31-.062-.739-.058-1.05-.046l-.048.002zm2.094 2.025z"/>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %} 
        </div>  
        {% if not polls %}
            <h2 class="text-center">EMPTY</h2>
        {% endif %} 
        {% if polls.length > 10 %}
            <div class="container-center-column pagination" style="width: 100%;">
                <span class="step-links">
                    {% if polls.has_previous %}
                        <a class="btn btn-primary" href="?page=1">&laquo; First</a>
                        <a class="btn btn-primary" href="?page={{ polls.previous_page_number }}">Prev</a>
                    {% else %}
                        <button class="btn btn-outline-default">&laquo; first</button>
                        <button class="btn btn-outline-default">Prev</button>
                    {% endif %}
            
                    <span class="current">
                        {{ polls.number }}/{{ polls.paginator.num_pages }}
                    </span>
            
                    {% if polls.has_next %}
                        <a class="btn btn-primary" href="?page={{ polls.next_page_number }}">Next</a>
                        <a class="btn btn-primary" href="?page={{ polls.paginator.num_pages }}">Last &raquo;</a>
                    {% else %}
                        <button class="btn btn-outline-default">Next</button>
                        <button class="btn btn-outline-default">Last &raquo;</button>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    </div>
{% endblock body %}

polls/templates/polls/input_key.html
{% extends 'theSP/layout.html' %}

{% block title %} Provide Key {% endblock title%}

{% block body %} 
    <div class="container-center-column" style="height: 100vh;">
        {% if error_message %}
            <div class="error_message"><h2 class="text-danger text-center">{{error_message}}</h2></div>
        {% endif %}
        <div class="form-box-small">
            <h2>Access Key</h2>
            <form action="{% url 'polls:input_key' poll_name=poll_name %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input autofocus class="form-control" type="password" name="key" placeholder="Key" required>
                </div>
                <br>
                <input class="btn btn-primary" type="submit" value="Proceed">
            </form>   
        </div>
    </div>
{% endblock body %}

polls/templates/polls/management.html
{% extends 'theSP/layout.html' %}
{% load static %}
{% block title %} Settings and Management{% endblock title%}

{% block script %}
    <script > 
        const POLL_NAME = "{{poll.name}}"  
        const PAGE_VIEW = "{{view}}" 
        const POLL_IS_ACTIVE = "{{poll.active}}"  
    </script>
    <script type="text/babel" src="{% static 'polls/js/categories_mgt.js' %}" ></script>
    <script type="text/babel" src="{% static 'polls/js/candidates_mgt.js' %}" ></script>
    <script type="text/babel" src="{% static 'polls/js/settings.js' %}" ></script>
    <script type="text/babel" src="{% static 'polls/js/poll_management.js' %}" ></script>

{% endblock script %}

{% block body %}
    <div class="header poll_header" style="margin-bottom:0%">
        <img src="{{poll.image.url}}" > 
        <div class="text">         
            <h1>{{poll.name}}</h1>
        </div>
    </div>
    <div id="body">

    </div>
{% endblock body %}

polls/templates/polls/results.html
{% extends 'theSP/layout.html' %}
{% load static %}
{% block title %} Results{% endblock title%}

{% block script %}
    <script>
        const POLL_NAME = "{{poll_name}}"
        const POLL_ACTIVE = "{{poll_active}}"

    </script>
    <script type="text/babel" src="{% static 'polls/js/results.js' %}">  </script> 
{% endblock script %}


{% block body %}
    <div class="header poll_header" style="margin-bottom:0%">
        <img src="{{image.url}}" > 
        <div class="text">         
            <h1>{{poll.name}}</h1>
        </div>
    </div>
    <div id="body">
        
    </div>
{% endblock body %}

polls/templates/polls/results_index.html
{% extends 'theSP/layout.html' %}
{% load static %}

{% block title %} Results {% endblock title%}

{% block body %}

    <div class="container" style="margin-top: 10em;">
        <div class="index row">
            {% for poll in polls %}
                <div class="index-card col-md-12 index-card-lg ">
                    <div class="card">
                        <div class="image">
                            <img src={{poll.image.url}} alt="image-{{poll.name}}">
                        </div>
                        <div class="details">
                            <h2 class="name capitalize" style="margin-top: 2em;">
                                {{poll.name}} 
                            </h2>
                            {% if not poll.active or poll.live_results %}
                                <a href = "{{poll.get_poll_results_url}}" style="margin-bottom: 2em;">SEE RESULTS</a>
                            {% else %}
                                <p>RESULTS UNAVAILABLE</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %} 
        </div> 
        {% if not polls %}
            <h2 class="text-center">EMPTY</h2>
        {% endif %} 

        {% if polls.length > 10 %}
            <div class="container-center-column pagination" style="width: 100%;">
                <span class="step-links">
                    {% if results_interested.has_previous %}
                        <a class="btn btn-primary" href="?page=1">&laquo; First</a>
                        <a class="btn btn-primary" href="?page={{ results_interested.previous_page_number }}">Prev</a>
                    {% else %}
                        <button class="btn btn-outline-default">&laquo; first</button>
                        <button class="btn btn-outline-default">Prev</button>
                    {% endif %}
            
                    <span class="current">
                        {{ results_interested.number }}/{{ results_interested.paginator.num_pages }}
                    </span>
            
                    {% if results_interested.has_next %}
                        <a class="btn btn-primary" href="?page={{ results_interested.next_page_number }}">Next</a>
                        <a class="btn btn-primary" href="?page={{ results_interested.paginator.num_pages }}">Last &raquo;</a>
                    {% else %}
                        <button class="btn btn-outline-default">Next</button>
                        <button class="btn btn-outline-default">Last &raquo;</button>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    </div>
{% endblock body %}

polls/templates/polls/voting.html
{% extends 'theSP/layout.html' %}
{% load static %}
{% block title %} Voting{% endblock title%}


{% block script %}
    <script>
        const POLL_NAME = "{{poll.name}}"
        const PREVIEW = "{{preview}}"
        document.addEventListener('DOMContentLoaded', function() {
            const voted_already = document.querySelector("#voted-already")
            document.querySelector("#close_voted-already").addEventListener('click',function(){
                voted_already.style.display = "none"
            })
        })
    </script>
    <script type="text/babel" src="{% static 'polls/js/voting.js' %}">  </script> 
{% endblock script %}

{% block body %}
    {% if not poll.active %}
        {% if not preview %}
            <div class= "container-center-column container-overlay">
                <h1 class="text-center" style="color: blue;">Voting Is Closed</h1>
            </div>
        {% endif %}
    {% endif %}
    <div id="voted-already" style="display: none;">
        <div class="container-overlay">
            <div class="container-center-column">
                <div class="pop-up">
                    <h2 class="message">YOU HAVE ALREADY VOTED IN THIS CATEGORY</h2>
                    <button id="close_voted-already">CLOSE</button> 
                </div>
            </div>
        </div>
    </div>

    <div class="header poll_header" style="margin-bottom:0%">
        <img src="{{poll.image.url}}" > 
        <div class="text">         
            <h1>{{poll.name}}</h1>
        </div>
    </div>

    <div id="body">
    </div>
{% endblock body %}