capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("user.urls")),
    path('',include("polls.urls")),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

user/urls.py
from django.urls import path
from . import views


app_name = "user"

urlpatterns = [
    # SignIn and Registration
    path('register/',views.register_view,name='register'),
    path('login/',views.login_view,name="login" ),
    path('logout/',views.logout_view,name="logout" ),
    path('activate/<str:username>/', views.activate_user, name="activate_user"),
    
    # Profile page
    path('user/profile/', views.user_profile, name="user_profile"),

    # Edits
    path('user/edit/', views.edit_profile, name="edit_profile"),
    path('reset_password/<int:user_id>/' ,views.reset_password_page, name = "reset_password_page"),
    path('send_reset_email/' ,views.reset_password_email, name = "reset_password_email"),
    path('user/change_password/', views.change_password, name = "change_password"),
]

user/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    confirm_password = forms.CharField(widget = forms.PasswordInput())
    country_code = forms.CharField(max_length = 10)
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    other_names = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=False)
    class Meta:
        model = User
        help_texts ={
            'username':None
        }
        fields =(
            "username",
            "first_name",
            "last_name",
            "other_names",
            "email",
            "phone_number",
            "profile_picture",
            "password",
            "date_of_birth"
        )
        
    def clean_password(self):
        password = self.cleaned_data["password"]
        # Password must be atleast 6 characters
        if len(password) > 5 : 
            return password
        raise forms.ValidationError("Password must be atleast 6 characters")
    
    def clean_confirm_password(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        print(password,confirm_password)
        if confirm_password != password:
            raise forms.ValidationError("Passwords don't match")
        return confirm_password
    
    def clean_phone_number(self):
        country_code = self.cleaned_data.get("country_code")
        phone_number = self.cleaned_data.get("phone_number")
        # phone_number must be atleast 9 characters
        if len(phone_number) < 9 : 
            raise forms.ValidationError("phone number must be atleast 9 characters")
        user = User.objects.filter(country_code=country_code,phone_number=phone_number)
        if user:
            raise forms.ValidationError("phone number already exists")
        return phone_number

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]
        if len(first_name) < 2 :
            raise forms.ValidationError("First name must be atleast 2 characters")
        if len(first_name.split()) > 1 : 
            raise forms.ValidationError("First name must be only one word")
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]
        if len(last_name) < 2: 
            raise forms.ValidationError("Last name must be atleast 2 characters")
        if len(last_name.split()) > 1 : 
            raise forms.ValidationError("Last name must be only one word")
        return last_name
        
class ChangePasswordForm(forms.Form):
    new_password = forms.CharField(widget = forms.PasswordInput(attrs={
        'class':'form-control',  
    }))
    confirm_password = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control'}))

    def clean_new_password(self):
        new_password = self.cleaned_data["new_password"]
        # Password must be atleast 6 characters
        if len(new_password) > 5 : 
            return new_password
        raise forms.ValidationError("Password must be atleast 6 characters")
    
    def clean_confirm_password(self):
        new_password = self.cleaned_data.get("new_password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if confirm_password != new_password:
            raise forms.ValidationError("Passwords don't match")
        return confirm_password

class EditProfileForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    other_names = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=False)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
    new_profile_picture = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control-file'}),required=False)

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]
        if len(first_name) < 2 :
            raise forms.ValidationError("First name must be atleast 2 characters")
        if len(first_name.split()) > 1 : 
            raise forms.ValidationError("First name must be only one word")
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]
        if len(last_name) < 2: 
            raise forms.ValidationError("Last name must be atleast 2 characters")
        if len(last_name.split()) > 1 : 
            raise forms.ValidationError("Last name must be only one word")
        return last_name

user/views.py
import random
import os
# import environ
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
# from twilio.rest import Client
from .models import User, ActivationCode
from .forms import UserForm, ChangePasswordForm, EditProfileForm

HOST = "http://127.0.0.1:8000"
# env = environ.Env()
# environ.Env.read_env()

########### Account Registration And Activation ############

# Sign in/login of activated users
def login_view(request):
    # If a user is already logged in redirect to homepage
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("polls:index"))

    error_message = ""

    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"].lower()
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        # If authentication successful
        if user is not None:
            # Cache current user logged in
            login(request, user)
            return HttpResponseRedirect(reverse("polls:index"))

        # If authentication failed
        else:
            error_message = "Invalid"
            # Check and redirect if user needs to be activated
            try:
                user = User.objects.get(username = username)
                if user.is_active == False:
                    return HttpResponseRedirect(reverse("user:activate_user",kwargs={"username":username}))
            # User does not exist
            except User.DoesNotExist:
                error_message ="User not found"
    return render(request,"user/login.html",context={"error_message":error_message})

# Log user out
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("user:login"))

# Register new user
def register_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("polls:index"))
    user_form = UserForm()
    error_messages = []

    if request.method == "POST":
        user_form = UserForm(request.POST, request.FILES)
        if user_form.is_valid():
            username = user_form.cleaned_data["username"]
            email = user_form.cleaned_data["email"]
            first_name = user_form.cleaned_data["first_name"]
            last_name = user_form.cleaned_data["last_name"]
            other_names = user_form.cleaned_data["other_names"]
            country_code = user_form.cleaned_data["country_code"] 
            phone_number = user_form.cleaned_data["phone_number"]
            profile_picture = request.FILES.get('profile_picture',False)
            password = user_form.cleaned_data["password"]
            date_of_birth = user_form.cleaned_data["date_of_birth"]
            
            # Attempt to create new user
            try:
                user = User.objects.create_user(
                    username = username, 
                    email = email, 
                    password = password,
                    first_name = first_name,
                    last_name = last_name,
                    other_names = other_names,
                    country_code = country_code,
                    phone_number = phone_number,
                    date_of_birth = date_of_birth,
                    profile_picture = profile_picture
                )
                # All new accounts are inactive until activated by otp code
                user.is_active = False
                user.save()
                create_activation_code(user.username)
                return HttpResponseRedirect(reverse("user:activate_user",kwargs={"username":username}))
            except IntegrityError:
                error_messages.append("Username already taken")
            except Exception as e:
                error_messages.append(e)
        else:  
            # Display all error fields as error message
            for field in user_form:   
                for error in field.errors:   
                    error_messages.append(error.capitalize())
    context ={
        "form":user_form,
        "error_messages":error_messages
    }
    return render(request, "user/register.html",context)

# Create a four key activation code
def create_activation_code(username):
    print("create activation code")
    code = random.randint(1000,9999) #simple code
    user = User.objects.get(username = username)
    # Check if user already has an activation code created and replace code
    try:
        user_activation = ActivationCode.objects.get(user = user)
        user_activation.code = code
        user_activation.save()
    #If user does not have activation code create new code for user
    except ActivationCode.DoesNotExist:
        new_activation_code = ActivationCode()
        new_activation_code.code = code
        new_activation_code.user = user
        new_activation_code.save()

    # Send activation code to users mobile using twilio api services
    # account_sid = env('ACCOUNT_SID')
    # auth_token = env('AUTH_TOKEN')
    # client = Client(account_sid, auth_token)
    try:
        # message = client.messages.create(
        #                                     body =f"Hello {user.first_name}, Your activation code is {code}",
        #                                     from_ =env('NUMBER'),
        #                                     to=user.phone_number
        #                                 )
        # print(message.sid)
        print(f"{username} activation code",code)
    except Exception:
        # Delete user if send otp failed; most likely phone number invalid
        user.delete()
       
        
# User atempt to activate account with key received
def activate_user(request, username):
    username = username.lower()
    # If user already activated redirect to home page
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("polls:index"))

    error_message = ""

    # Check if user exists in table for activation
    try:
        user = User.objects.get(username = username)
        user_code = ActivationCode.objects.get(user = user)
    except Exception:
        raise Http404
    
    if request.method == "POST":
        #Resend activation code to user phone  
        if request.POST["form_type"] == 'resend_code':
            create_activation_code(username)
            error_message = "Check your phone for code"
        
        # Try to activate user
        else:
            # Get database code
            code = user_code.code
            # Get user code input
            confirm_code = request.POST["code"]
            # Compare input with code and activate if same
            if code == confirm_code:
                user.is_active = True
                user.save()
                # delete activation code
                user_code.delete()
                return HttpResponseRedirect(reverse("user:login"))
            else:
                error_message = "Incorrect Code"

    context={
        "error_message":error_message,
        "username":username
    }
    return render(request, "user/activate_user.html",context)

############ Account Editing ##################

# Signed in user changes password
@login_required(login_url = 'user:login')
def change_password(request):
    user = request.user
    error_message = ""
    
    if request.POST:
        user = authenticate(username=user.username, password = request.POST["current_password"])
        # Check if authentication successful
        if user is not None:
            form = ChangePasswordForm(request.POST)
            if form.is_valid(): 
                if form.cleaned_data['new_password'] == form.cleaned_data['confirm_password'] :
                    user.set_password(form.cleaned_data['new_password'])
                    user.save()
                    return HttpResponseRedirect(reverse('user:logout')) 
            error_message = "New password invalid"
        else:
            error_message = "Current password is incorrect"

    context = {
        "form": ChangePasswordForm(),
        "error_message":error_message
    }
    return render(request,"user/change_password.html",context)

# Send link for password reset to user's email
def reset_password_email(request):
    error_message = ""

    if request.method == "POST":
        email = request.POST["email"].lower()
        try:
            user = User.objects.get(email = email)
            token = user.password
            reset_link = f'{HOST}/reset_password/{user.id}/'
            print("This is the link for password reset (email)", reset_link, "  token is ",token)
            subject = "The SP Password Reset"
            body = f"Hello {user.first_name} {user.last_name}. Your token is --->     {token}        <---.Go to {reset_link}  to reset your password with token"
            receiver = user.email
            send_mail(
                subject,
                body,
                "",
                [receiver]
            )
            return HttpResponseRedirect(reverse("user:login"))
        except User.DoesNotExist:
            error_message = "Incorrect Email"
        except Exception as e:
            print(e)
            error_message = "Could not send mail to this email"
            # return HttpResponseRedirect(reverse("user:login"))
    context ={
        "error_message":error_message
    }
    return render(request, "user/reset_password_email.html", context)

# Link to enable users who forgot password to reset password
def reset_password_page(request,user_id):
    error_message = ""
    try:
        user = User.objects.get(id = user_id)
    except User.DoesNotExist:
        raise Http404

    if request.POST:
        token = request.POST["token"]

user/templates/user/activate_user.html
{% extends 'theSP/layout.html' %}

{% block title %} Activate Profile {% endblock title%}

{% block body %}
    <div class="container-fluid">
        <div>
            {% if error_message %}
            <div class="error_message"></div><h2 class="text-danger text-center">{{ error_message }}</h2></div>
            {% endif %}
            <div class="container-center-column">
                <div class="form-box-small" style="margin-top: 2em;">
                    <h2>Enter Code To Activate Account</h2>
                    <div>
                        <form  action="{% url 'user:activate_user' username=username %}" method="POST">
                            {% csrf_token %}
                            <input name="form_type" value="activate_form" readonly hidden>
                            <div class="form-group">
                                <input class="form-control" name="code" type="number">
                            </div>
                            <div class="form-group container-center-row">
                                <input class="btn btn-primary" type="submit">
                            </div>
                        </form>
                    </div>
                    <form  action="{% url 'user:activate_user' username=username %}" method="POST">
                        {% csrf_token %}
                        <input name="form_type" value="resend_code" readonly hidden>
                        
                        <div class="container-center-row">
                            <p style="color: black;font-size: 1.5rem;">Didn't receive code?</p>
                            <button class="btn btn-link"><p style="font-weight: 600;">Resend</</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

user/templates/user/change_password.html
{% extends 'theSP/layout.html' %}

{% block title %} Change Password {% endblock title%}

{% block body %}

    <div class="container-fluid" style="height:100vh;">  
        {% if error_message %}
            <div class="error_message"><h2 class="text-danger text-center">{{ error_message }}</h2></div>
        {% endif %}
        <div class="container-center-column" style="height: 100%;">
            <div class="form-box-small">
                <form action="{% url 'user:change_password' %}" method="post">
                    {% csrf_token %}
                    <p>
                        <label for="id_current_password">Current Password: </label>
                        <input class="form-control" type="password" name="current_password" id="id_current_password" required>
                    </p>
                    {{form.as_p}}
                    <input class="btn btn-primary" type="submit">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

user/templates/user/edit_profile.html
{% extends 'theSP/layout.html' %}

{% block title %} Edit Profile {% endblock title%}


{% block body %}
    {% if error_message %}
        <div class="error_message"> <h2 class="text-danger text-center">{{ error_message }}</h2> </div>
    {% endif %}
    <div class="container-fluid">
        <div class='container background-glass'>
            <div class="square-animate" style="--i:0"></div>
            <div class="square-animate" style="--i:1"></div>
            <div class="square-animate" style="--i:2"></div>
            <div class="square-animate" style="--i:3"></div>
            <div class="square-animate" style="--i:4"></div>
            <div class="square-animate" style="--i:5"></div>
        </div>
        <div class="container-center-column">  
            <div class="form-box-large" style="z-index:30">
                <h2>Edit Profile</h2>
                
                <form class="form-group" action="{% url 'user:edit_profile' %}" method="post" enctype="multipart/form-data" style="text-align:center">
                    {% csrf_token %}
                    {% for instance in form %}
                        <div class="form-group">
                            {{instance.label_tag}}     
                            {{instance}}                  
                        </div>
                    {% endfor %}
                    <input class="btn btn-primary"  type="submit" style="margin-top:1em">
                    <div class="container-center-row lone-btn">
                        <button type="button" id="delete_account" class="btn btn-danger" style="color: white;margin-top: 2em;">DELETE ACCOUNT</button>
                    </div>
                </form>
            </div>
        </div>
        <script>
            const delete_account = document.getElementById('delete_account')
            delete_account.addEventListener('click', ()=> deleteAccount())
            function deleteAccount(){
                if(confirm("ARE YOU SURE YOU WANT TO DELETE YOUR ACCOUNT?")){
                    fetch(`${window.location}`,{
                        method:"DELETE",
                        headers: {
                            "X-CSRFToken": getCookie("csrftoken")
                        }
                    })
                    .then(response=>{
                        console.log(response)
                    })
                }
            }
        </script>  
    </div>
{% endblock body %}

user/templates/user/login.html
{% extends 'theSP/layout.html' %}

{% block title %} Login {% endblock title%}

{% block body %} 
    <div class="container-center-column" style="height: 100vh;">
        {% if error_message %}
            <div class="error_message"><h2 class="text-danger text-center">{{error_message}}</h2></div>
        {% endif %}
        <div class="form-box-small">
            <h2>Login</h2>
            <form action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
                <br>
                <input class="btn btn-primary" id="login_submit_button" type="submit" value="Login">
            </form>
            <p>Don't have an account? <a href="{% url 'user:register' %}">Sign Up</a></p>
            <p>Forgot your password? <a href="{% url 'user:reset_password_email' %}">Click Here</a></p>    
        </div>
    </div>
{% endblock body %}

user/templates/user/register.html
{% extends 'theSP/layout.html' %}

{% block title %} Register {% endblock title%}


{% block body %}

    {% if error_messages %}
        {% for error in error_messages %}
            <div class="error_message"><h2 class="text-danger text-center">{{error}}</h2></div>
        {% endfor %}
    {% endif %}
    <div class="container-fluid">
        <div class='container background-glass'>
            <div class="square-animate" style="--i:0"></div>
            <div class="square-animate" style="--i:1"></div>
            <div class="square-animate" style="--i:2"></div>
            <div class="square-animate" style="--i:3"></div>
            <div class="square-animate" style="--i:4"></div>
            <div class="square-animate" style="--i:5"></div>
        </div>
        <div class="container-center-column">
            <div class="form-box-large" style="z-index:30">
                <h2>Register</h2>
                <form action="{% url 'user:register' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- {{form.as_p}} -->
                    <div class="form-group">
                        <label for="inputUsername">Username</label>
                        <input id="inputUsername" class="form-control" type="text" name="username" required>                  
                    </div>

                    <div class="form-group">
                        <label for="inputFirstname">First Name</label>
                        <input id ="inputFirstname" class="form-control" type="text" name="first_name" required>                
                    </div>

                    <div class="form-group">
                        <label for="inputlastname">last Name</label>
                        <input id="inputlastname" class="form-control" type="text" name="last_name"  required>                 
                    </div>

                    <div class="form-group">
                        <label for="inputOthernames">Other Names</label>
                        <input id="inputOthernames" class="form-control" type="text" name="other_names" >                
                    </div>

                    <div class="form-group">
                        <label for="dob">Date OF Birth</label>
                        <input id="dob" class="form-control" type="date" name="date_of_birth" required>                
                    </div>

                    <div class="form-group">
                        <label for="inputEmail">Email</label>
                        <input id="inputEmail" class="form-control" type="email" name="email" required>                
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="inputZip"> + Zip</label>
                            <input type="number" class="form-control" id="inputZip" name="country_code" value="233" step="1">
                          </div>
                        <div class="form-group col-md-10">
                          <label for="inputPhone">Phone Number</label>
                          <input type="number" class="form-control" id="inputPhone" name="phone_number" step="1" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="profile_picture">Upload Profile Picture</label>
                        <input id ="profile_picture" class="form-control-file" name="profile_picture" type="file" >                
                    </div>

                    <div class="form-group">
                        <label for="password">Password</label>
                        <input id="password" class="form-control" type="password" name="password" required>               
                    </div>

                    <div class="form-group">
                        <label for="confirm_password">Confirm Password</label>
                        <input id="confirm_password"  class="form-control" type="password" name="confirm_password" required>                
                    </div>
                    <div class="container-center-column" style="margin-top: 2em;">
                        <input class="btn btn-primary btn-lg"  type="submit" value="Register">
                    </div>
                </form>
                <div class="container-center-column">
                    <p>Already have an account? <a href="{% url 'user:login' %}">Log In here.</a></p>
                </div>
            </div>
        </div>

    </div>

    

{% endblock body %}

user/templates/user/reset_password_email.html
{% extends 'theSP/layout.html' %}

{% block title %} Reset Password {% endblock title%}

{% block body %}

    {% if error_message %}
        <div class="error_message"><h2 class="text-danger text-center">{{ error_message }}</h2></div>   
    {% endif %}
    <div class="container-center-column">
        <div class="form-box-large"> 
            <h2> Enter Email </h2>
            <form action="{% url 'user:reset_password_email' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" name = "email" type="email">
                </div>
                <input class="btn btn-primary" type="submit">
            </form>
        </div>
    </div>  
{% endblock body %}

user/templates/user/reset_password_token.html
{% extends 'theSP/layout.html' %}

{% block title %} Reset Password {% endblock title%}

{% block body %}

    {% if error_message %}
        <div class="error_message"><h2 class="text-danger text-center">{{ error_message }}</h2></div>
    {% endif %}   
    <div class="container-fluid" style="margin-top: 5em;">  
        <div class="container-center-column">
            <div class="form-box-small">
                <form action="{% url 'user:reset_password_page' user_id=user_id %}" method="post">
                    {% csrf_token %} 
                    <p>
                        <label for="id_token">Provide Token: </label>
                        <input class="form-control" type="password" name="token" id="id_token" required>
                    </p>
                    {{form.as_p}}
                    <input class="btn btn-primary" type="submit"> 
                </form>
            </div>
        </div>
    </div>  
{% endblock body %}

user/templates/user/user_profile.html
{% extends 'theSP/layout.html' %}

{% block title %} Profile {% endblock title%}

{% block body %}

    <main class="container-fluid">   
        <div class="container-fluid background-glass">      
            <div class="color"></div>
            <div class="color"></div>
            <div class="color"></div>
            
            <div class="square-animate" style="--i:0"></div>
            <div class="square-animate" style="--i:1"></div>
            <div class="square-animate" style="--i:2"></div>
            <div class="square-animate" style="--i:3"></div>
            <div class="square-animate" style="--i:4"></div>
            <div class="square-animate" style="--i:5"></div>
        </div>
        <div class="container-center-column profile">
            <div class="image" >
                    {% if request.user.profile_picture %}
                        <img src="{{request.user.profile_picture.url}}" class="rounded-circle" alt="profile picture">    
                    {% else %}
                        No Profile Image
                    {% endif %}
            </div>
            <div class="username">
                <h4>Username : {{request.user.username}}</h4>
            </div>

            <div class="name">
                <h4>Name : {{request.user.first_name}} {{request.user.other_names}} {{request.user.last_name}}</h4>
            </div>

            <div class="phone">
                <h4>Phone : +{{request.user.country_code}}-{{request.user.phone_number}}</h4>
            </div>

            <div class="email">
                <h4>Email : {{request.user.email}}</h4>
            </div>

            <div class="edit">
                <a class="btn btn-primary btn-lg" href="{% url 'user:edit_profile' %}" >
                    <strong>
                        Edit Profile
                    </strong>
                </a>
                <a class="btn btn-primary btn-lg" href="{% url 'user:change_password' %}"><strong>Change Password</strong></a>
            </div>    
        </div>
    </main>    
{% endblock body %}