capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("user.urls")),
    path('',include("polls.urls")),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.index, name="index"),
    # Index of user polls, add new poll
    path('myIndex/',views.my_polls,name='my_index'),
    # Voting Page
    path('polls/votingPage/<str:poll_name>/',views.votingPage,name='voting_page'),
    path('polls/votingPage/<str:poll_name>/<str:preview>/',views.votingPage,name='voting_pagePreview'),

    # Get poll groups - javascript fetch api
    path('polls/getGroups/<str:poll_name>/',views.get_groups,name='getGroups'),
    # Get group categories - javascript fetch api
    path('polls/getCategories/<str:poll_name>/<str:group_name>/',views.get_categories,name='getCategories'),
    # Get category candidates - javascript fetch api
    path('polls/getCandidates/<str:poll_name>/<str:category_name>/',views.get_candidates,name='getCandidates'),
    # Vote - javascript fetch api
    path('polls/vote/<str:poll_name>/',views.vote,name='vote'),
    # Results
    path('polls/resultsIndex/',views.results_index,name='results_index'),
    path('polls/results/<str:poll_name>/',views.resultsPage,name='resultsPage'),
    path('polls/get_results/<str:poll_name>/<str:category_name>/<str:sort>/',views.results,name='results'),
    
    ## MANAGEING POLL(ADMIN/CREATOR)
    # Manage poll, add category, add candidate
    path('polls/manage/<str:poll_name>/<str:view>/',views.poll_management,name='poll_management'),

    # Get all categories
    path('polls/<str:poll_name>/management/categories/', views.manage_categories, name ="categories_management"),

    # Get all candidates
    path('polls/<str:poll_name>/management/candidates/', views.manage_candidates, name ="candidates_management"),

    # Manage settings
    path('polls/<str:poll_name>/management/settings/', views.manage_settings, name ="settings_management"),

    # Manage keys
    path('polls/<str:poll_name>/management/keys/', views.poll_keys, name ="keys_management"),

    # Keys Upload and Print(Excel)
    path('polls/<str:poll_name>/Excelkeys/', views.excel_keys, name ="keys_excel"),

     # Input Key
    path('polls/<str:poll_name>/inputKey/', views.input_key, name ="input_key")

]

user/urls.py
from django.urls import path
from . import views


app_name = "user"

urlpatterns = [
    # SignIn and Registration
    path('register/',views.register_view,name='register'),
    path('login/',views.login_view,name="login" ),
    path('logout/',views.logout_view,name="logout" ),
    path('activate/<str:username>/', views.activate_user, name="activate_user"),
    
    # Profile page
    path('user/profile/', views.user_profile, name="user_profile"),

    # Edits
    path('user/edit/', views.edit_profile, name="edit_profile"),
    path('reset_password/<int:user_id>/' ,views.reset_password_page, name = "reset_password_page"),
    path('send_reset_email/' ,views.reset_password_email, name = "reset_password_email"),
    path('user/change_password/', views.change_password, name = "change_password"),
]

polls/forms.py
from django import forms
from .models import Poll, Candidate

class PollForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control-file'}))
    closing_date = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control','type':'date'}))

    class Meta:
        model = Poll
        fields = ('name','image','closing_date','restrictionType','live_results')

    def __init__(self, *args, **kwargs):
        super(PollForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Title"

class CandidateForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    party = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=False)
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control-file'}),required=False)

    class Meta:
        model = Candidate
        fields= "__all__"
        exclude=['poll','categories_contesting']

class EditPollForm(forms.Form):
    name = forms.CharField()
    image = forms.ImageField(required=False)
    restrictionType = forms.CharField()
    closing_date = forms.DateField()
    live_results = forms.BooleanField(required=False)

class KeyForm(forms.Form):
    key = forms.CharField()

polls/views.py
from django.http.response import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
import json
import pandas
from io import BytesIO


from .models import Poll, PollCategory, Candidate, PollCategoryGroup, RestrictionKey, Vote
from .forms import PollForm, CandidateForm, EditPollForm, KeyForm

# Page of active and unhidden polls
def index(request):
    polls = Poll.objects.filter(active=True, hidden=False)
    paginator = Paginator(polls, 10) # Show 10 items per page.
    page_number = request.GET.get('page')
    polls = paginator.get_page(page_number)
    context ={
        "polls":polls,
        "page":"home"
    }
    return render(request, "polls/index.html",context)

# Index of all created polls and add new poll form
@login_required(login_url = 'user:login')
def my_polls(request):
    form = PollForm()
    error_messages = []
    
    # Create a new poll
    if request.method == "POST":
        # # Limit number of user polls to 3
        # if Poll.objects.filter(creator = request.user).count() > 2:
        #     error_messages.append("User can only create a maximum of 3 polls")

        form = PollForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                Poll.objects.create(
                    creator = request.user,
                    name = form.cleaned_data['name'],
                    image = form.cleaned_data['image'] ,
                    closing_date = form.cleaned_data['closing_date'],
                    restrictionType = form.cleaned_data['restrictionType'],
                    live_results = form.cleaned_data['live_results'] 
                )
                return HttpResponseRedirect(reverse('polls:my_index'))
            except Exception as e:
                error_messages.append(e)
                print(e)
        else:
            for field in form:   
                for error in field.errors:   
                    error_messages.append(error.capitalize())

    polls = Poll.objects.filter(creator = request.user)
    paginator = Paginator(polls, 10) # Show 10 items per page.
    page_number = request.GET.get('page')
    polls = paginator.get_page(page_number)

    context ={
        "form":form,
        "polls":polls,
        "error_messages":error_messages,
        "page":"myPolls"
    }
    return render(request, "polls/my_index.html",context)

# Get available groups for the poll, returned as json
@login_required(login_url = 'user:login')
def get_groups(request,poll_name):
    poll_name = poll_name.lower()
    poll = Poll.objects.get(name = poll_name)
    groups = poll.groups.all()
    return JsonResponse([group.serialize() for group in groups],safe=False)

# Get available candidates for the selected category, returned as json
@login_required(login_url = 'user:login')
def get_candidates(request,poll_name,category_name):
    poll_name = poll_name.lower()
    category_name = category_name.lower()
    category = PollCategory.objects.get(poll__name = poll_name, name = category_name)
    candidates = category.candidates.all()
    return JsonResponse([candidate.serialize() for candidate in candidates],safe=False)

# Get available categories for the poll either all or by the group selected, returned as json
@login_required(login_url = 'user:login')
def get_categories(request,poll_name,group_name):
    poll_name = poll_name.lower()
    group_name = group_name.lower()
    poll = Poll.objects.get(name = poll_name)
    if group_name == "none":
        categories = poll.categories.all()
    else:   
        group= poll.groups.all().get(name = group_name)
        categories = group.categories.all()
    return JsonResponse([category.serialize() for category in categories],safe=False)

# Manage poll settings, groups, categories and candidates
@login_required(login_url = 'user:login')
def poll_management(request,poll_name,view):
    poll_name = poll_name.lower()
    view = view.lower()
    poll = Poll.objects.get(name = poll_name)
    poll.deadline() # check and update poll status considering the poll deadline
    # Check for creator and give access or deny
    if poll.creator != request.user:
        raise Http404
    # Default view is categories if none of the accepted views is provided
    if view != "categories" and view !="candidates" and view != "settings":
        view = "categories"
    context ={
        "view":view,
        "poll":poll,
    }
    return render(request, "polls/management.html",context)

# Handle api requests to poll categories for creation, editing, deleting of poll category
@login_required(login_url = 'user:login')
def manage_categories(request,poll_name):
    poll_name = poll_name.lower()
    poll = Poll.objects.get(name = poll_name)

    # Check for creator and give access
    if poll.creator != request.user:
        raise Http404
    # Return poll categories in json
    if request.method == "GET":
        categories = poll.categories.all()
        return JsonResponse([category.serialize() for category in categories],safe=False)

    # Can only edit, create and delete only inactive polls
    if poll.active:
        return HttpResponse(status = 403)
    elif request.method == "POST":
        data = json.loads(request.body)
        # Get new polls name from json data
        name = data['name']
        # Default group selected to none
        group = None
        # Get the group object if a group was provided
        if data['group']:
            try:
                group = poll.groups.all.get(name = data["group"])
            except Exception as e:
                print(e)
        # Check against empty name and then save new poll
        if name.split():
            try:
                PollCategory.objects.create(
                    poll = poll,
                    name = name,
                    group = group
                )
                return HttpResponse(status = 201)
            except Exception as e:
                print(e)
                return HttpResponse(status = 400)

    # Editing an already existing category
    elif request.method == "PUT":
        data = json.loads(request.body)
        # Select category by id provided
        category_id = data['id']
        category = poll.categories.all().get(id = category_id)
        
        # Request to remove link of all candidates to this category
        if data['action'] == "clear_candidates":
            candidates = category.candidates.all()
            for candidate in candidates:
                candidate.categories_contesting.remove(category)
            return HttpResponse(status = 201)
        
        # Handle replacing category name and also changing the group it is under
        new_name = data['name']
        new_group_name = data['group_name']

        if new_name.split():
            category.name = new_name
        if new_group_name:
            new_group = poll.groups.all().get(name = new_group_name)
            category.group = new_group
        try:
            category.save()
            return HttpResponse(status = 201)
        except Exception as e:
            print(e)
            return HttpResponse(status=400)

    # Delete category from the poll
    elif request.method == "DELETE":
        data = json.loads(request.body)
        category_id = data['id']
        category = poll.categories.all().get(id = category_id)
        category.delete()
        return HttpResponse(status = 201)

# Handle access, creation and deletion of candidates to poll
@login_required(login_url = 'user:login')
def manage_candidates(request,poll_name):
    poll_name = poll_name.lower()
    poll = Poll.objects.get(name = poll_name)

    # Check for creator and give access or deny
    if poll.creator != request.user:
        raise Http404
    
    # Return all candidates data in json 
    if request.method == "GET":
        candidates = poll.candidates.all()
        return JsonResponse([candidate.serialize() for candidate in candidates],safe=False)
    
    # Cannot edit or save candidate in an active poll
    if poll.active:
        return HttpResponse(status = 403)
        
    elif request.method == "POST":
        candidate_form = CandidateForm(request.POST , request.FILES)
        categories = request.POST["categories"].split(',')   
        print(request.POST['party'])
        if candidate_form.is_valid():
            print(candidate_form.cleaned_data["party"])
            # Create a new candidate
            if request.POST['form_type'] == "new_candidate":
                try:
                    candidate = Candidate.objects.create(
                        poll = poll,
                        name = candidate_form.cleaned_data["name"],
                        party = candidate_form.cleaned_data["party"],
                        image = candidate_form.cleaned_data["image"]
                    )
                    for category in categories:
                        try:
                            category = poll.categories.all().get(name = category)
                            candidate.categories_contesting.add(category)
                        except Exception as e:
                            print(e)
                    candidate.save()
                    return HttpResponse(status=201)
                except Exception as e:
                    print("error: ",e)

            # Edit an already existing candidate's data
            elif request.POST['form_type'] == "edit_candidate":
                candidate = poll.candidates.all().get(id = request.POST['candidate_id'])
                candidate.name = candidate_form.cleaned_data["name"]
                candidate.party = candidate_form.cleaned_data["party"] 
                new_image = candidate_form.cleaned_data["image"]
                candidate.categories_contesting.clear()
                if new_image:

polls/templates/theSP/error.html
{% extends 'theSP/layout.html' %}

{% block title %} Error {% endblock title%}

{% block body %}
    <h1>{{message}}</h1>
{% endblock body %}

polls/templates/theSP/footer.html
<p>This is CS50</p>
<a href="https://rayhantabase.github.io">Salim Abdulai</a>

polls/templates/theSP/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <meta http-equiv="Cache-control" content="no-store">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">  
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora|Ubuntu:400,700&display=swap" > 
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'dependencies/css/bootstrap.min.css' %}" >     
        <script src="{% static 'dependencies/js/jquery.min.js/' %}"></script>
        <script src="{% static 'dependencies/js/react.development.js/' %}" ></script>
        <script src="{% static 'dependencies/js/react-dom.development.js/' %}" ></script>
        <script src="{% static 'dependencies/js/babel.min.js/' %}" ></script> 
        <script src="{% static 'dependencies/js/bootstrap.min.js/' %}" ></script> 
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            } 
            const HOST = "http://127.0.0.1:8000"
        </script>
        {% block script %}
        {% endblock script %}
    </head>
    
    <body>
        <section style="min-height: 80vh;">
            {% include 'theSP/nav_bar.html' %}
            {% block body %}
            {% endblock body %}  
        </section>

        <section>
            <footer>
                {% include 'theSP/footer.html' %}
            </footer>
        </section>
    </body>
</html>

polls/templates/theSP/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="z-index: 100;">
    <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarLayout" aria-controls="navbarLayout" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarLayout">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <li {% if page == "home" %} class="nav-iten active" {% else %} class="nav-item" {% endif %}>
                    <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
                </li>
                <li {% if page == "myPolls" %} class="nav-iten active" {% else %} class="nav-item" {% endif %}>
                    <a class="nav-link" href="{% url 'polls:my_index' %}">My Polls</a>
                </li>
                <li {% if page == "results" %} class="nav-iten active" {% else %} class="nav-item" {% endif %}>
                    <a class="nav-link" href="{% url 'polls:results_index' %}">Results</a>
                </li>
                <li {% if page == "profile" %} class="nav-iten active" {% else %} class="nav-item" {% endif %}>
                    <a class="nav-link" href="{% url 'user:user_profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                </li>
            {% endif %}

            {% comment %} <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li> {% endcomment %}
        </ul>
    </div>
</nav>